[RunMode]
;Режим запуска программы
;ALL - паук + сервер (последовательно)
;SPIDER_ONLY - только паук
;SERVER_ONLY - только сервер
mode = SERVER_ONLY

[DB]
;Настройки базы данных
host = localhost
port = 5432
dbname = postgres
user = postgres
password = 1989
erase = false ;если флаг установлен в true выполняется обнуление БД при каждом запуске паука

[Spider]
;Настройки паука
start = orsk.ru
depth = 3

[Server]
;Настройки сервера
ip = 0.0.0.0
port = 8080